<a href="https://colab.research.google.com/github/dj-1087/BigContest-COIN/blob/master/After_May_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [4]:
import pandas as pd
PATH = "/content/gdrive/My Drive/Colab Notebooks/2차_최종_데이터/"
pitcher_r_vs = pd.read_csv(PATH+"2차_최종_최근_상대_팀투수.csv")
hitter_r_vs = pd.read_csv(PATH+"2차_최종_최근_상대_팀타자.csv")
pitcher_r = pd.read_csv(PATH+"2차_최종_최근_팀투수.csv")
hitter_r = pd.read_csv(PATH+"2차_최종_최근_팀타자.csv")

In [7]:
def after_may(df):
    team_list = []
    for year in range(2016, 2021):
        a = df[(df['일자'] > '{}-05-10'.format(year)) & (df['시즌'] == year)]
        team_list.append(a)
    df = pd.concat(team_list)
    return df

In [8]:
pitcher_r_vs = after_may(pitcher_r_vs)
pitcher_r_vs = pitcher_r_vs.reset_index()
pitcher_r = after_may(pitcher_r)
pitcher_r = pitcher_r.reset_index()
hitter_r_vs = after_may(hitter_r_vs)
hitter_r_vs = hitter_r_vs.reset_index()
hitter_r = after_may(hitter_r)
hitter_r = hitter_r.reset_index()

In [9]:
hitter_r_vs

      index            게임키          일자  ...  상대최근득점권타수 상대최근득점권안타  상대최근득점권타율
0       297  20160511KTHT0  2016-05-11  ...   7.666667  2.333333   0.304348
1       298  20160511KTHT0  2016-05-11  ...  12.333333  2.666667   0.216216
2       299  20160511NCHH0  2016-05-11  ...   6.000000  1.333333   0.222222
3       300  20160511NCHH0  2016-05-11  ...  10.000000  2.666667   0.266667
4       301  20160511OBSK0  2016-05-11  ...   7.666667  1.666667   0.217391
...     ...            ...         ...  ...        ...       ...        ...
4874   6326  20200719LTSS0  2020-07-19  ...  12.000000  3.666667   0.305556
4875   6327  20200719OBHT0  2020-07-19  ...   9.000000  0.666667   0.074074
4876   6328  20200719OBHT0  2020-07-19  ...   9.666667  3.000000   0.310345
4877   6329  20200719WOSK0  2020-07-19  ...   6.333333  2.000000   0.315789
4878   6330  20200719WOSK0  2020-07-19  ...  12.000000  3.333333   0.277778

[4879 rows x 68 columns]

In [11]:
pitcher_r_vs.to_csv("/content/gdrive/My Drive/Colab Notebooks/AfterMay_DF/pitcher_r_vs.csv",index=False)
pitcher_r.to_csv("/content/gdrive/My Drive/Colab Notebooks/AfterMay_DF/pitcher_r.csv",index=False)
hitter_r_vs.to_csv("/content/gdrive/My Drive/Colab Notebooks/AfterMay_DF/hitter_r_vs.csv",index=False)
hitter_r.to_csv("/content/gdrive/My Drive/Colab Notebooks/AfterMay_DF/hitter_r.csv",index=False)

In [4]:
starter_relief = after_may(starter_relief)
starter_relief = starter_relief.reset_index()

In [6]:
starter_relief.to_csv("/content/gdrive/My Drive/Colab Notebooks/AfterMay_DF/starter_relief.csv",index=False)

In [5]:
starter_relief

      index           G_ID     GDAY_DS T_ID  ...   선발_OSLG   구원_OSLG   tR        aR
0       306  20160511KTHT0  2016-05-11   HT  ...  0.413844  0.382637  139  4.793103
1       307  20160511KTHT0  2016-05-11   KT  ...  0.435009  0.415020  170  5.483871
2       308  20160511NCHH0  2016-05-11   HH  ...  0.495025  0.452160  221  7.366667
3       309  20160511NCHH0  2016-05-11   NC  ...  0.343042  0.326409  115  3.965517
4       310  20160511OBSK0  2016-05-11   SK  ...  0.391185  0.401055  146  4.424242
...     ...            ...         ...  ...  ...       ...       ...  ...       ...
4923   6395  20200719LTSS0  2020-07-19   LT  ...  0.417591  0.431442  320  5.245902
4924   6396  20200719OBHT0  2020-07-19   HT  ...  0.387865  0.415655  282  4.622951
4925   6397  20200719OBHT0  2020-07-19   OB  ...  0.419591  0.422989  348  5.523810
4926   6398  20200719WOSK0  2020-07-19   SK  ...  0.378891  0.454439  338  5.281250
4927   6399  20200719WOSK0  2020-07-19   WO  ...  0.404072  0.439378  332  5.107692

[4928 rows x 74 columns]