<a href="https://colab.research.google.com/github/dj-1087/BigContest-COIN/blob/master/Binary_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [ ]:
from google.colab import files
import io
import pandas as pd

myfile = files.upload()

In [ ]:
raw = pd.read_csv(io.BytesIO(myfile["raw 전체.csv"]))
raw['일자'] = pd.to_datetime(raw['일자'],format='%Y%m%d', errors='raise')
raw['시즌'] = raw['일자'].dt.year
raw["일자"]

KeyError: ignored

In [ ]:
team_list = []
for year in range(2016, 2021):
  a = raw[(raw['일자'] > '{}-05-10'.format(year)) & (raw['시즌'] == year)]
  team_list.append(a)
raw = pd.concat(team_list)
raw

In [ ]:
raw["시즌"]

In [ ]:
raw = pd.concat([raw[raw["시즌"]==2018],raw[raw["시즌"]==2019]],axis=0)
raw

In [ ]:
raw.to_csv("/content/gdrive/My Drive/Colab Notebooks/Sample_DF/2018_2019.csv",index=False)

In [ ]:
myfile

In [ ]:
PATH = "/content/gdrive/My Drive/Colab Notebooks/1차_최종_데이터(08_29)/"
team_pitcher = pd.read_csv(PATH+"1차_최종_팀투수.csv", encoding="CP949")
team_hitter = pd.read_csv(PATH+"1차_최종_팀타자.csv")
per_pitcher = pd.read_csv(PATH+"1차_최종_개인투수.csv")
per_hitter = pd.read_csv(PATH+"1차_최종_개인타자.csv")
team_pitcher_r = pd.read_csv(PATH+"1차_최종_최근_팀투수.csv")
team_hitter_r = pd.read_csv(PATH+"1차_최종_최근_팀타자.csv")
team_pitcher_vs = pd.read_csv(PATH+"1차_최종_상대_팀투수.csv")
team_hitter_vs = pd.read_csv(PATH+"1차_최종_상대_팀타자.csv")
final_common = pd.read_csv(PATH+"1차_최종_공통.csv")

In [ ]:
team_hitter

               G_ID     GDAY_DS T_ID VS_T_ID  ...   SECA     PSN   RBI_PCT   RUN_PCT
0     20160401HHLG0  2016-04-01   LG      HH  ...  0.000   0.000  0.000000  0.000000
1     20160401HHLG0  2016-04-01   HH      LG  ...  0.000   0.000  0.000000  0.000000
2     20160401HTNC0  2016-04-01   NC      HT  ...  0.000   0.000  0.000000  0.000000
3     20160401HTNC0  2016-04-01   HT      NC  ...  0.000   0.000  0.000000  0.000000
4     20160401KTSK0  2016-04-01   SK      KT  ...  0.000   0.000  0.000000  0.000000
...             ...         ...  ...     ...  ...    ...     ...       ...       ...
6395  20200719LTSS0  2020-07-19   LT      SS  ...  0.241  48.816  0.097378  0.101124
6396  20200719OBHT0  2020-07-19   HT      OB  ...  0.256  29.506  0.101124  0.116105
6397  20200719OBHT0  2020-07-19   OB      HT  ...  0.252  40.220  0.144404  0.155235
6398  20200719WOSK0  2020-07-19   SK      WO  ...  0.220  41.528  0.130435  0.137681
6399  20200719WOSK0  2020-07-19   WO      SK  ...  0.307  58.959  0.184783  0.195652

[6400 rows x 52 columns]

In [ ]:
def after_may(df):
    team_list = []
    for year in range(2016, 2021):
        a = df[(df['GDAY_DS'] > '{}-05-10'.format(year)) & (df['GYEAR'] == year)]
        team_list.append(a)
    df = pd.concat(team_list)
    return df

In [ ]:
team_hitter = after_may(team_hitter)
team_hitter = team_hitter.reset_index()
team_hitter

      index           G_ID     GDAY_DS T_ID  ...   SECA     PSN   RBI_PCT   RUN_PCT
0       306  20160511KTHT0  2016-05-11   HT  ...  0.274  20.870  0.107843  0.117647
1       307  20160511KTHT0  2016-05-11   KT  ...  0.251  26.963  0.145631  0.155340
2       308  20160511NCHH0  2016-05-11   HH  ...  0.238  18.158  0.078652  0.078652
3       309  20160511NCHH0  2016-05-11   NC  ...  0.271  19.478  0.157895  0.168421
4       310  20160511OBSK0  2016-05-11   SK  ...  0.244  28.070  0.100719  0.100719
...     ...            ...         ...  ...  ...    ...     ...       ...       ...
4923   6395  20200719LTSS0  2020-07-19   LT  ...  0.241  48.816  0.097378  0.101124
4924   6396  20200719OBHT0  2020-07-19   HT  ...  0.256  29.506  0.101124  0.116105
4925   6397  20200719OBHT0  2020-07-19   OB  ...  0.252  40.220  0.144404  0.155235
4926   6398  20200719WOSK0  2020-07-19   SK  ...  0.220  41.528  0.130435  0.137681
4927   6399  20200719WOSK0  2020-07-19   WO  ...  0.307  58.959  0.184783  0.195652

[4928 rows x 53 columns]

In [ ]:
team_pitcher = after_may(team_pitcher)
team_pitcher = team_pitcher.reset_index()
team_pitcher

      index           G_ID     GDAY_DS T_ID  ...   OAVG   OOBP   OSLG   OOPS
0       306  20160511KTHT0  2016-05-11   HT  ...  0.279  0.359  0.404  0.763
1       307  20160511KTHT0  2016-05-11   KT  ...  0.277  0.361  0.426  0.787
2       308  20160511NCHH0  2016-05-11   HH  ...  0.304  0.405  0.469  0.873
3       309  20160511NCHH0  2016-05-11   NC  ...  0.237  0.316  0.337  0.653
4       310  20160511OBSK0  2016-05-11   SK  ...  0.248  0.333  0.395  0.727
...     ...            ...         ...  ...  ...    ...    ...    ...    ...
4923   6395  20200719LTSS0  2020-07-19   LT  ...  0.271  0.335  0.423  0.758
4924   6396  20200719OBHT0  2020-07-19   HT  ...  0.266  0.331  0.398  0.729
4925   6397  20200719OBHT0  2020-07-19   OB  ...  0.289  0.352  0.421  0.773
4926   6398  20200719WOSK0  2020-07-19   SK  ...  0.272  0.358  0.409  0.766
4927   6399  20200719WOSK0  2020-07-19   WO  ...  0.281  0.339  0.419  0.759

[4928 rows x 61 columns]

In [ ]:
team_hitter = team_hitter.drop("RUN",axis=1)
team_pitcher = team_pitcher.drop("R", axis=1)

In [ ]:
def binaryData(df):
    for i in range(0,len(df),2):
        for j in range(0,len(df.columns)):
            if type(df.iloc[i,j])==str:
                continue
            if df.iloc[i,j]>df.iloc[i+1,j]:
                df.iloc[i,j] = 1
            else:
                df.iloc[i,j] = 0
    df = df.drop(range(1,len(df),2))
    return df

In [ ]:
team_hitter = binaryData(team_hitter)
team_pitcher = binaryData(team_pitcher)

In [ ]:
team_hitter

      index           G_ID     GDAY_DS T_ID  ... SECA  PSN RBI_PCT  RUN_PCT
0         0  20160511KTHT0  2016-05-11   HT  ...  1.0  0.0     0.0      0.0
2         0  20160511NCHH0  2016-05-11   HH  ...  0.0  0.0     0.0      0.0
4         0  20160511OBSK0  2016-05-11   SK  ...  0.0  1.0     0.0      0.0
6         0  20160511SSLG0  2016-05-11   LG  ...  0.0  0.0     0.0      0.0
8         0  20160511WOLT0  2016-05-11   LT  ...  1.0  1.0     0.0      0.0
...     ...            ...         ...  ...  ...  ...  ...     ...      ...
4918      0  20200719HHLG0  2020-07-19   LG  ...  1.0  1.0     1.0      1.0
4920      0  20200719KTNC0  2020-07-19   NC  ...  1.0  1.0     1.0      0.0
4922      0  20200719LTSS0  2020-07-19   SS  ...  1.0  1.0     1.0      1.0
4924      0  20200719OBHT0  2020-07-19   HT  ...  1.0  0.0     0.0      0.0
4926      0  20200719WOSK0  2020-07-19   SK  ...  0.0  0.0     0.0      0.0

[2464 rows x 52 columns]

In [ ]:
team_pitcher

      index           G_ID     GDAY_DS T_ID  ... OAVG  OOBP OSLG  OOPS
0         0  20160511KTHT0  2016-05-11   HT  ...  1.0   0.0  0.0   0.0
2         0  20160511NCHH0  2016-05-11   HH  ...  1.0   1.0  1.0   1.0
4         0  20160511OBSK0  2016-05-11   SK  ...  0.0   0.0  1.0   0.0
6         0  20160511SSLG0  2016-05-11   LG  ...  1.0   1.0  1.0   1.0
8         0  20160511WOLT0  2016-05-11   LT  ...  1.0   1.0  1.0   1.0
...     ...            ...         ...  ...  ...  ...   ...  ...   ...
4918      0  20200719HHLG0  2020-07-19   LG  ...  0.0   0.0  0.0   0.0
4920      0  20200719KTNC0  2020-07-19   NC  ...  0.0   0.0  0.0   0.0
4922      0  20200719LTSS0  2020-07-19   SS  ...  0.0   1.0  0.0   0.0
4924      0  20200719OBHT0  2020-07-19   HT  ...  0.0   0.0  0.0   0.0
4926      0  20200719WOSK0  2020-07-19   SK  ...  0.0   1.0  0.0   1.0

[2464 rows x 60 columns]

In [ ]:
range(1,len(team_hitter),2)

range(1, 2464, 2)

In [ ]:
team_hitter.columns

Index(['index', 'G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC ',
       'PA', 'AB', 'RBI', 'HIT', 'H2', 'H3', 'HR', 'SB', 'CS', 'SH', 'SF',
       'BB', 'IB', 'HP', 'KK', 'GD', 'ERR', 'LOB', 'P_HRA_RT ', 'P_AB_CN',
       'P_HIT_CN', 'GYEAR', 'H1', 'OBP', 'SLG', 'OPS', 'GPA', 'AVG', 'BABIP',
       'ISO', 'HR_PCT', 'K_PCT', 'BB_PCT', 'BBK', 'wOBA', 'wRAA', 'wRC', 'RC',
       'RC27', 'XR', 'SPD', 'SECA', 'PSN', 'RBI_PCT', 'RUN_PCT'],
      dtype='object')

In [ ]:
team_pitcher.columns

Index(['index', 'G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC ',
       'CG_CK', 'WLS', 'HOLD', 'INN2', 'BF', 'PA', 'AB', 'HIT', 'H2', 'H3',
       'HR', 'SB', 'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'WP', 'BK',
       'ERR', 'ER', 'P_WHIP_RT', 'P2_WHIP_RT', 'CB_WHIP_RT', 'GYEAR', 'ERA',
       'RA9', 'ERC', 'FIP', 'kwERA', 'LOB', 'HR_PCT', 'K_PCT', 'BB_PCT', 'K9',
       'BB9', 'HR9', 'KBB', 'whip', 'P_G', 'P_IP', 'P_PA', 'PFR', 'CYP', 'F_E',
       'R_E', 'OAVG', 'OOBP', 'OSLG', 'OOPS'],
      dtype='object')

In [ ]:
team_hitter = team_hitter.drop(labels=['index', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC ',
       'PA', 'AB', 'RBI', 'HIT', 'H2', 'H3', 'HR', 'SB', 'CS', 'SH', 'SF',
       'BB', 'IB', 'HP', 'KK', 'GD', 'ERR', 'LOB', 'P_HRA_RT ', 'P_AB_CN',
       'P_HIT_CN', 'GYEAR',],axis=1)
team_pitcher = team_pitcher.drop(labels=["index","GDAY_DS","INN2",'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC ',
       'CG_CK', 'HOLD', 'INN2', 'BF', 'PA', 'AB', 'HIT', 'H2', 'H3',
       'HR', 'SB', 'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'WP', 'BK',
       'ERR', 'ER', 'P_WHIP_RT', 'P2_WHIP_RT', 'CB_WHIP_RT', 'GYEAR',],axis=1)

In [ ]:
team_pitcher_vs.columns

Index(['G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC ', 'CG_CK',
       'WLS', 'HOLD', 'INN2', 'BF', 'PA', 'AB', 'HIT', 'H2', 'H3', 'HR', 'SB',
       'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'WP', 'BK', 'ERR', 'R',
       'ER', 'P_WHIP_RT', 'P2_WHIP_RT', 'CB_WHIP_RT', 'GYEAR', 'vs_ERA',
       'vs_RA9', 'vs_ERC', 'vs_FIP', 'vs_kwERA', 'vsLOB', 'vs_HR_PCT',
       'vs_K_PCT', 'vs_BB_PCT', 'vs_K9', 'vs_BB9', 'vs_HR9', 'vs_KBB',
       'vs_whip', 'vs_PFR', 'vs_P_G', 'vs_P_IP', 'vs_P_PA', 'vs_CYP', 'vs_F_E',
       'vs_R_E', 'vs_OAVG', 'vs_OOBP', 'vs_OSLG', 'vs_OOPS'],
      dtype='object')

In [ ]:
team_hitter.to_csv("/content/gdrive/My Drive/Colab Notebooks/Sample_DF/binary_team_hitter.csv",index=False)
team_pitcher.to_csv("/content/gdrive/My Drive/Colab Notebooks/Sample_DF/binary_team_pitcher.csv",index=False)