In [19]:
import pandas as pd
#ip = individual pitcher
PATH_IP = "C:/Users/home/DA(inflearn)/individual_pitcher/2020빅콘테스트 문제데이터(데이터분석분야-퓨처스리그)/2020빅콘테스트 데이터분석분야-퓨쳐스리그_스포츠투아이_제공데이터(.CSV)_시즌별, 시트별 구분/2020빅콘테스트_스포츠투아이_제공데이터_개인투수_"
#tp = team pitcher
PATH_TP = "C:/Users/home/DA(inflearn)/individual_pitcher/2020빅콘테스트 문제데이터(데이터분석분야-퓨처스리그)/2020빅콘테스트 데이터분석분야-퓨쳐스리그_스포츠투아이_제공데이터(.CSV)_시즌별, 시트별 구분/2020빅콘테스트_스포츠투아이_제공데이터_팀투수_"
season = [2016, 2017, 2018, 2019, 2020]

# 개인

In [20]:
def load_csv(PATH, season):
    doc_ip = None
    for i in season:
        doc_i = pd.read_csv(PATH+str(i)+".csv")
        doc_ip = pd.concat([doc_ip,doc_i], axis=0)
    doc_ip = doc_ip.set_index(pd.Index(range(0,doc_ip.shape[0])))
    return doc_ip
df = load_csv(PATH_IP, season)
df

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,P_ID,START_CK,RELIEF_CK,CG_CK,...,KK,GD,WP,BK,ERR,R,ER,P_WHIP_RT,P2_WHIP_RT,CB_WHIP_RT
0,20160401HHLG0,20160401,LG,HH,0,B,60146,0,1,0,...,3,0,0,0,0,0,0,0.000000,1.000000,1.50
1,20160401HHLG0,20160401,LG,HH,0,B,61891,0,1,0,...,1,0,0,0,0,0,0,0.000000,1.800000,1.50
2,20160401HHLG0,20160401,LG,HH,0,B,62146,0,1,0,...,0,0,0,0,0,0,0,0.000000,3.000000,0.00
3,20160401HHLG0,20160401,LG,HH,0,B,62698,1,0,0,...,4,1,0,0,0,4,4,0.818182,1.588235,3.75
4,20160401HHLG0,20160401,HH,LG,0,T,65764,0,1,0,...,1,0,0,0,0,1,1,0.000000,1.500000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27799,20200719WOSK0,20200719,WO,SK,0,T,67313,1,0,0,...,7,0,1,0,0,0,0,0.000000,1.000000,2.25
27800,20200719WOSK0,20200719,WO,SK,0,T,67391,0,1,0,...,1,0,0,0,0,0,0,0.000000,0.000000,0.00
27801,20200719WOSK0,20200719,WO,SK,0,T,68341,0,1,0,...,2,0,1,0,0,4,4,0.000000,0.000000,1.50
27802,20200719WOSK0,20200719,WO,SK,0,T,69399,0,1,0,...,0,0,0,0,0,0,0,3.000000,3.000000,0.00
27803,20200719WOSK0,20200719,SK,WO,0,B,75138,0,1,0,...,0,0,0,0,0,0,0,0.000000,0.000000,0.00

# PFR: (삼진+볼넷)/이닝

In [21]:
def convert_PFR(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","P_ID"]).sum()
    needs = needs[["KK","BB","INN2"]]
    needs["INN2"] = needs["INN2"]/3
    pfr = (needs["KK"]+needs["BB"])/needs["INN2"]
    return pfr
pfr = convert_PFR(df)
pfr

G_ID  P_ID
2016  60105    0.352941
      60146    1.268293
      60164    0.750000
      60181    1.174603
      60263    1.472585
                 ...
2020  79545    2.062500
      79764    0.837209
      79825    0.666667
      79847    1.147059
      99445    0.441176
Length: 1240, dtype: float64

# 팀

In [22]:
def load_csv(PATH, season):
    doc_tp = None
    for i in season:
        doc_i = pd.read_csv(PATH+str(i)+".csv")
        doc_tp = pd.concat([doc_tp,doc_i], axis=0)
    doc_tp = doc_tp.set_index(pd.Index(range(0,doc_tp.shape[0])))
    return doc_tp
team_df = load_csv(PATH_TP, season)
team_df

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,CG_CK,WLS,HOLD,INN2,...,KK,GD,WP,BK,ERR,R,ER,P_WHIP_RT,P2_WHIP_RT,CB_WHIP_RT
0,20160401HHLG0,20160401,LG,HH,0,B,0,W,0,36,...,10,1,0,0,0,4,4,0.642857,1.285714,2.400000
1,20160401HHLG0,20160401,HH,LG,0,T,0,L,0,34,...,11,0,1,0,0,5,4,1.500000,1.000000,0.750000
2,20160401HTNC0,20160401,NC,HT,0,B,0,W,0,27,...,10,1,2,0,0,4,4,1.333333,1.038462,2.142857
3,20160401HTNC0,20160401,HT,NC,0,T,0,L,0,24,...,9,1,0,0,0,5,5,0.500000,1.695652,1.875000
4,20160401KTSK0,20160401,SK,KT,0,B,0,L,0,27,...,7,0,0,0,0,8,8,1.000000,2.357143,2.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,20200719LTSS0,20200719,LT,SS,0,T,0,W,2,27,...,9,1,0,0,0,1,1,0.600000,1.111111,1.500000
6396,20200719OBHT0,20200719,HT,OB,0,B,0,L,0,27,...,4,0,0,0,0,8,8,2.142857,1.800000,0.750000
6397,20200719OBHT0,20200719,OB,HT,0,T,0,W,1,27,...,5,1,0,0,0,4,4,3.000000,1.000000,1.875000
6398,20200719WOSK0,20200719,SK,WO,0,B,0,W,0,27,...,4,1,0,0,0,3,3,1.500000,1.105263,2.142857
6399,20200719WOSK0,20200719,WO,SK,0,T,0,L,2,24,...,10,0,2,0,0,4,4,1.800000,1.312500,1.333333

In [23]:
def convert_team_PFR(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","T_ID"]).sum()
    needs = needs[["KK","BB","INN2"]]
    needs["INN2"] = needs["INN2"]/3
    pfr = (needs["KK"]+needs["BB"])/needs["INN2"]
    return pfr
team_pfr = convert_team_PFR(team_df)
team_pfr

G_ID  T_ID
2016  HH      1.245487
      HT      1.195925
      KT      1.209741
      LG      1.124515
      LT      1.258752
      NC      1.292822
      OB      1.149366
      SK      1.155416
      SS      1.133091
      WO      1.038792
2017  HH      1.068342
      HT      1.100000
      KT      1.071656
      LG      1.109461
      LT      1.221906
      NC      1.219772
      OB      1.102484
      SK      1.118311
      SS      1.257284
      WO      1.095987
2018  HH      1.252747
      HT      1.150577
      KT      1.125294
      LG      1.191014
      LT      1.333680
      NC      1.223892
      OB      1.164770
      SK      1.219927
      SS      1.209803
      WO      1.120905
2019  HH      1.150815
      HT      1.170886
      KT      1.040720
      LG      1.131429
      LT      1.242329
      NC      1.147677
      OB      0.965983
      SK      1.182357
      SS      1.134605
      WO      1.059421
2020  HH      1.327230
      HT      1.193746
      KT      1.046838
      LG      1.138470
      LT      1.114440
      NC      1.206294
      OB      1.114486
      SK      1.260666
      SS      1.118881
      WO      1.042955
dtype: float64

In [32]:
team_pitcher = pd.read_csv("C:/Users/home/DA(inflearn)/individual_pitcher/팀투수_세이버 매트릭스_합본.csv")
team_pitcher

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,완투,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,1,20160401HHLG0,2016-04-01,HH,LG,0,T,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,2,20160401HTNC0,2016-04-01,NC,HT,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,3,20160401HTNC0,2016-04-01,HT,NC,0,T,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,4,20160401KTSK0,2016-04-01,SK,KT,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,6395,6395,635,20200719LTSS0,2020-07-19,LT,SS,0,T,0,...,0.679640,0.030008,0.174134,6.774665,3.091352,1.167479,2.191489,149.557377,16.668088,3.842881
6396,6396,6396,636,20200719OBHT0,2020-07-19,HT,OB,0,B,0,...,0.684932,0.020524,0.199127,7.675810,3.114090,0.791147,2.464865,145.836066,16.638404,3.881326
6397,6397,6397,637,20200719OBHT0,2020-07-19,OB,HT,0,T,0,...,0.654102,0.019154,0.166800,6.697923,3.188724,0.769139,2.100503,154.793651,17.362611,3.879077
6398,6398,6398,638,20200719WOSK0,2020-07-19,SK,WO,0,B,0,...,0.683666,0.023089,0.176354,7.102732,4.248812,0.929929,1.671698,154.640625,17.631235,3.933625
6399,6399,6399,639,20200719WOSK0,2020-07-19,WO,SK,0,T,0,...,0.679494,0.026994,0.167204,6.506969,2.696864,1.050523,2.412791,146.261538,16.562718,3.825755

In [33]:
team_pitcher.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', '게임키', '일자', '팀코드',
       '상대팀코드', '더블헤더코드', '초말', '완투', '결과', '홀드', '이닝*3', '투구수', '타자', '타수',
       '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비', '4구', '고4', '사구',
       '삼진', '병살타', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP', '2점차이하WHIP',
       '345번타자WHIP', '시즌', '평균자책점', 'RA/9', 'ERC', 'FIP', 'LOB', '홈런율', '삼진율',
       'K9', 'BB9', 'HR9', 'KBB', 'P/G', 'P/IP', 'P/PA'],
      dtype='object')

In [34]:
pitcher = pd.read_csv("C:/Users/home/DA(inflearn)/individual_pitcher/개인투수_세이버 매트릭스_합본.csv")
pitcher

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,60146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,1,20160401HHLG0,2016-04-01,LG,HH,0,B,61891,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,2,20160401HHLG0,2016-04-01,LG,HH,0,B,62146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,3,20160401HHLG0,2016-04-01,LG,HH,0,B,62698,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,4,20160401HHLG0,2016-04-01,HH,LG,0,T,65764,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27799,27799,27799,2882,20200719WOSK0,2020-07-19,WO,SK,0,T,67313,...,0.763889,0.030928,0.185567,7.043478,3.130435,1.173913,2.250000,146.261538,16.782609,3.938776
27800,27800,27800,2883,20200719WOSK0,2020-07-19,WO,SK,0,T,67391,...,0.614035,0.019608,0.205882,7.985915,3.422535,0.760563,2.333333,146.261538,17.197183,3.990196
27801,27801,27801,2884,20200719WOSK0,2020-07-19,WO,SK,0,T,68341,...,0.697674,0.027027,0.270270,9.642857,4.821429,0.964286,2.000000,146.261538,14.785714,3.729730
27802,27802,27802,2885,20200719WOSK0,2020-07-19,WO,SK,0,T,69399,...,0.461538,0.000000,0.075472,3.724138,3.724138,0.000000,1.000000,146.261538,18.103448,3.301887
27803,27803,27803,2886,20200719WOSK0,2020-07-19,SK,WO,0,B,75138,...,0.869565,0.076923,0.153846,6.000000,6.000000,3.000000,1.000000,154.640625,17.000000,3.923077

In [35]:
pitcher.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', '게임키', '일자', '팀코드',
       '상대팀코드', '더블헤더코드', '초말', '선수코드', '선발', '구원', '완투', '종료', '결과', '홀드',
       '이닝*3', '투구수', '타자', '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루.1', '희타',
       '희비', '4구', '고4', '사구', '삼진', '병살', '폭투', '보크', '실책', '실점', '자책점',
       '득점권WHIP', '2점차이하WHIP', '345번타자WHIP', '시즌', '평균자책점', 'RA/9', 'ERC',
       'FIP', 'LOB', '홈런율', '삼진율', 'K9', 'BB9', 'HR9', 'KBB', 'P/G', 'P/IP',
       'P/PA'],
      dtype='object')

In [36]:
def pfr(row):
    previous = team_pitcher[(team_pitcher['시즌'] == row['시즌']) & (team_pitcher['팀코드'] == row['팀코드']) & (team_pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['PFR'] = 0
        return row
    previous_sum = previous.sum()
    try:
        pg = (previous_sum["삼진"]+previous_sum["4구"])/(previous_sum["이닝*3"]/3)
    except ZeroDivisionError:
        row['PFR'] = 0
    row["PFR"] = pg
    return row
def perPFR(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    previous_sum = previous.sum()
    if len(previous) == 0:
        row['PFR'] = 0
        return row
    try:
        pg = (previous_sum["삼진"]+previous_sum["4구"])/(previous_sum["이닝*3"]/3)
    except ZeroDivisionError:
        row['PFR'] = 0
        return row
    row['PFR'] = pg
    return row

In [37]:
team_pitcher = team_pitcher.apply(pfr,axis=1)
team_pitcher["PFR"].tail()

6395    1.110840
6396    1.202618
6397    1.112760
6398    1.268409
6399    1.027875
Name: PFR, dtype: float64

In [38]:
pitcher = pitcher.apply(perPFR,axis=1)
pitcher["PFR"]

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
27799    1.173913
27800    1.267606
27801    1.607143
27802    0.827586
27803    1.333333
Name: PFR, Length: 27804, dtype: float64

In [39]:
team_pitcher.to_csv("팀투수_세이버 매트릭스_합본.csv",encoding='utf-8-sig')
pitcher.to_csv("개인투수_세이버 매트릭스_합본.csv",encoding='utf-8-sig')

In [40]:
team_pitcher

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,완투,...,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA,PFR
0,0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,1,20160401HHLG0,2016-04-01,HH,LG,0,T,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,2,20160401HTNC0,2016-04-01,NC,HT,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,3,20160401HTNC0,2016-04-01,HT,NC,0,T,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,4,20160401KTSK0,2016-04-01,SK,KT,0,B,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,6395,6395,635,20200719LTSS0,2020-07-19,LT,SS,0,T,0,...,0.030008,0.174134,6.774665,3.091352,1.167479,2.191489,149.557377,16.668088,3.842881,1.110840
6396,6396,6396,636,20200719OBHT0,2020-07-19,HT,OB,0,B,0,...,0.020524,0.199127,7.675810,3.114090,0.791147,2.464865,145.836066,16.638404,3.881326,1.202618
6397,6397,6397,637,20200719OBHT0,2020-07-19,OB,HT,0,T,0,...,0.019154,0.166800,6.697923,3.188724,0.769139,2.100503,154.793651,17.362611,3.879077,1.112760
6398,6398,6398,638,20200719WOSK0,2020-07-19,SK,WO,0,B,0,...,0.023089,0.176354,7.102732,4.248812,0.929929,1.671698,154.640625,17.631235,3.933625,1.268409
6399,6399,6399,639,20200719WOSK0,2020-07-19,WO,SK,0,T,0,...,0.026994,0.167204,6.506969,2.696864,1.050523,2.412791,146.261538,16.562718,3.825755,1.027875

In [41]:
pitcher

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,...,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA,PFR
0,0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,60146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,1,20160401HHLG0,2016-04-01,LG,HH,0,B,61891,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,2,20160401HHLG0,2016-04-01,LG,HH,0,B,62146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,3,20160401HHLG0,2016-04-01,LG,HH,0,B,62698,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,4,20160401HHLG0,2016-04-01,HH,LG,0,T,65764,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27799,27799,27799,2882,20200719WOSK0,2020-07-19,WO,SK,0,T,67313,...,0.030928,0.185567,7.043478,3.130435,1.173913,2.250000,146.261538,16.782609,3.938776,1.173913
27800,27800,27800,2883,20200719WOSK0,2020-07-19,WO,SK,0,T,67391,...,0.019608,0.205882,7.985915,3.422535,0.760563,2.333333,146.261538,17.197183,3.990196,1.267606
27801,27801,27801,2884,20200719WOSK0,2020-07-19,WO,SK,0,T,68341,...,0.027027,0.270270,9.642857,4.821429,0.964286,2.000000,146.261538,14.785714,3.729730,1.607143
27802,27802,27802,2885,20200719WOSK0,2020-07-19,WO,SK,0,T,69399,...,0.000000,0.075472,3.724138,3.724138,0.000000,1.000000,146.261538,18.103448,3.301887,0.827586
27803,27803,27803,2886,20200719WOSK0,2020-07-19,SK,WO,0,B,75138,...,0.076923,0.153846,6.000000,6.000000,3.000000,1.000000,154.640625,17.000000,3.923077,1.333333