In [ ]:
import pandas as pd
#ip = individual pitcher
PATH_IP = "C:/Users/home/DA(inflearn)/individual_pitcher/2020빅콘테스트 문제데이터(데이터분석분야-퓨처스리그)/2020빅콘테스트 데이터분석분야-퓨쳐스리그_스포츠투아이_제공데이터(.CSV)_시즌별, 시트별 구분/2020빅콘테스트_스포츠투아이_제공데이터_개인투수_"
#tp = team pitcher
PATH_TP = "C:/Users/home/DA(inflearn)/individual_pitcher/2020빅콘테스트 문제데이터(데이터분석분야-퓨처스리그)/2020빅콘테스트 데이터분석분야-퓨쳐스리그_스포츠투아이_제공데이터(.CSV)_시즌별, 시트별 구분/2020빅콘테스트_스포츠투아이_제공데이터_팀투수_"
season = [2016, 2017, 2018, 2019, 2020]

# 개인

In [ ]:
def load_csv(PATH, season):
    doc_ip = None
    for i in season:
        doc_i = pd.read_csv(PATH+str(i)+".csv")
        doc_ip = pd.concat([doc_ip,doc_i], axis=0)
    doc_ip = doc_ip.set_index(pd.Index(range(0,doc_ip.shape[0])))
    return doc_ip
df = load_csv(PATH_IP, season)
df

# P/G: 경기당 투구수

In [141]:
def convert_PG(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"season"] = needs.at[i,"G_ID"][:4]
        needs.at[i,"count"] = 1
    needs = needs.groupby(by=["season","P_ID"]).sum()
    needs = needs[["BF", "count"]]
    pg = needs["BF"]/needs["count"]
    return pg
pg = convert_PG(df)
pg

season  P_ID
2016    60105    41.500000
        60146    19.315789
        60164    54.000000
        60181    20.568627
        60263    85.346154
                   ...
2020    79545    14.272727
        79764    52.800000
        79825    17.904762
        79847    65.166667
        99445    17.333333
Length: 1240, dtype: float64

# P/IP: 이닝당 투구수

In [ ]:
def convert_PIP(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","P_ID"]).sum()
    needs = needs[["INN2","BF"]]
    needs["INN2"] = needs["INN2"]/3
    pip = needs["BF"]/needs["INN2"]
    return pip
p_ip = convert_PIP(df)
p_ip

# P/PA: 타석당 투구수

In [ ]:
def convert_PPA(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","P_ID"]).sum()
    needs = needs[["BF","PA"]]
    ppa = needs["BF"]/needs["PA"]
    return ppa
p_pa = convert_PPA(df)
p_pa

# 팀

In [ ]:
def load_csv(PATH, season):
    doc_tp = None
    for i in season:
        doc_i = pd.read_csv(PATH+str(i)+".csv")
        doc_tp = pd.concat([doc_tp,doc_i], axis=0)
    doc_tp = doc_tp.set_index(pd.Index(range(0,doc_tp.shape[0])))
    return doc_tp
team_df = load_csv(PATH_TP, season)
team_df

# P/G: 경기당 투구수

In [ ]:
def convert_team_PG(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"season"] = needs.at[i,"G_ID"][:4]
        needs.at[i,"count"] = 1
    
    needs = needs.groupby(by=["season","T_ID"])
    pg = needs["BF"].mean()
    return pg
team_pg = convert_team_PG(team_df)
team_pg = team_pg.reset_index()
team_pg

# P/IP: 이닝당 투구수

In [ ]:
def convert_team_PIP(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","T_ID"]).sum()
    needs = needs[["INN2","BF"]]
    needs["INN2"] = needs["INN2"]/3
    pip = needs["BF"]/needs["INN2"]
    return pip
team_p_ip = convert_team_PIP(team_df)
team_p_ip

# P/PA: 타석당 투구수

In [ ]:
def convert_team_PPA(df):
    needs = df.copy()
    
    for i, row in needs.iterrows():
        needs.at[i,"G_ID"] = needs.at[i,"G_ID"][:4]
    needs = needs.groupby(by=["G_ID","T_ID"]).sum()
    needs = needs[["BF","PA"]]
    ppa = needs["BF"]/needs["PA"]
    return ppa
team_p_pa = convert_team_PPA(team_df)
team_p_pa

# 저장

In [124]:
team_pitcher = pd.read_csv("C:/Users/home/DA(inflearn)/individual_pitcher/팀투수_세이버 매트릭스_합본.csv")
team_pitcher

,Unnamed: 0,Unnamed: 0.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,완투,결과,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,0,W,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,20160401HHLG0,2016-04-01,HH,LG,0,T,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,20160401HTNC0,2016-04-01,NC,HT,0,B,0,W,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,20160401HTNC0,2016-04-01,HT,NC,0,T,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,20160401KTSK0,2016-04-01,SK,KT,0,B,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,6395,635,20200719LTSS0,2020-07-19,LT,SS,0,T,0,W,...,0.679640,0.030008,0.174134,6.774665,3.091352,1.167479,2.191489,149.557377,16.668088,3.842881
6396,6396,636,20200719OBHT0,2020-07-19,HT,OB,0,B,0,L,...,0.684932,0.020524,0.199127,7.675810,3.114090,0.791147,2.464865,145.836066,16.638404,3.881326
6397,6397,637,20200719OBHT0,2020-07-19,OB,HT,0,T,0,W,...,0.654102,0.019154,0.166800,6.697923,3.188724,0.769139,2.100503,154.793651,17.362611,3.879077
6398,6398,638,20200719WOSK0,2020-07-19,SK,WO,0,B,0,W,...,0.683666,0.023089,0.176354,7.102732,4.248812,0.929929,1.671698,154.640625,17.631235,3.933625
6399,6399,639,20200719WOSK0,2020-07-19,WO,SK,0,T,0,L,...,0.679494,0.026994,0.167204,6.506969,2.696864,1.050523,2.412791,146.261538,16.562718,3.825755

In [125]:
team_pitcher.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', '게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드',
       '초말', '완투', '결과', '홀드', '이닝*3', '투구수', '타자', '타수', '안타', '2루타', '3루타',
       '홈런', '도루', '도루실패', '희타', '희비', '4구', '고4', '사구', '삼진', '병살타', '폭투',
       '보크', '실책', '실점', '자책점', '득점권WHIP', '2점차이하WHIP', '345번타자WHIP', '시즌',
       '평균자책점', 'RA/9', 'ERC', 'FIP', 'LOB', '홈런율', '삼진율', 'K9', 'BB9', 'HR9',
       'KBB', 'P/G', 'P/IP', 'P/PA'],
      dtype='object')

In [126]:
pitcher = pd.read_csv("C:/Users/home/DA(inflearn)/individual_pitcher/개인투수_세이버 매트릭스_합본.csv")
pitcher

,Unnamed: 0,Unnamed: 0.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,선발,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,60146,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,20160401HHLG0,2016-04-01,LG,HH,0,B,61891,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,20160401HHLG0,2016-04-01,LG,HH,0,B,62146,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,20160401HHLG0,2016-04-01,LG,HH,0,B,62698,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,20160401HHLG0,2016-04-01,HH,LG,0,T,65764,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27799,27799,2882,20200719WOSK0,2020-07-19,WO,SK,0,T,67313,1,...,0.763889,0.030928,0.185567,7.043478,3.130435,1.173913,2.250000,146.261538,16.782609,3.938776
27800,27800,2883,20200719WOSK0,2020-07-19,WO,SK,0,T,67391,0,...,0.614035,0.019608,0.205882,7.985915,3.422535,0.760563,2.333333,146.261538,17.197183,3.990196
27801,27801,2884,20200719WOSK0,2020-07-19,WO,SK,0,T,68341,0,...,0.697674,0.027027,0.270270,9.642857,4.821429,0.964286,2.000000,146.261538,14.785714,3.729730
27802,27802,2885,20200719WOSK0,2020-07-19,WO,SK,0,T,69399,0,...,0.461538,0.000000,0.075472,3.724138,3.724138,0.000000,1.000000,146.261538,18.103448,3.301887
27803,27803,2886,20200719WOSK0,2020-07-19,SK,WO,0,B,75138,0,...,0.869565,0.076923,0.153846,6.000000,6.000000,3.000000,1.000000,154.640625,17.000000,3.923077

In [127]:
pitcher.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', '게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드',
       '초말', '선수코드', '선발', '구원', '완투', '종료', '결과', '홀드', '이닝*3', '투구수', '타자',
       '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루.1', '희타', '희비', '4구', '고4',
       '사구', '삼진', '병살', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP', '2점차이하WHIP',
       '345번타자WHIP', '시즌', '평균자책점', 'RA/9', 'ERC', 'FIP', 'LOB', '홈런율', '삼진율',
       'K9', 'BB9', 'HR9', 'KBB', 'P/G', 'P/IP', 'P/PA'],
      dtype='object')

# 게임별

In [128]:
def pg(row):
    previous = team_pitcher[(team_pitcher['시즌'] == row['시즌']) & (team_pitcher['팀코드'] == row['팀코드']) & (team_pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['P/G'] = 0
        return row
    previous_sum = previous.sum()
    try:
        pg = previous_sum["투구수"]/previous.count()[0]
    except ZeroDivisionError:
        row['P/G'] = 0
    row["P/G"] = pg
    return row
def perPG(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    previous_sum = previous.sum()
    if len(previous) == 0:
        row['P/G'] = 0
        return row
    try:
        pg = previous_sum["투구수"]/previous.count()[0]
    except ZeroDivisionError:
        row['P/G'] = 0
        return row
    row['P/G'] = pg
    return row

In [129]:
team_pitcher = team_pitcher.apply(pg,axis=1)
team_pitcher["P/G"].tail()

6395    149.557377
6396    145.836066
6397    154.793651
6398    154.640625
6399    146.261538
Name: P/G, dtype: float64

In [130]:
pitcher = pitcher.apply(pg,axis=1)
pitcher["P/G"]

0          0.000000
1          0.000000
2          0.000000
3          0.000000
4          0.000000
            ...
27799    146.261538
27800    146.261538
27801    146.261538
27802    146.261538
27803    154.640625
Name: P/G, Length: 27804, dtype: float64

In [131]:
def pip(row):
    previous = team_pitcher[(team_pitcher['시즌'] == row['시즌']) & (team_pitcher['팀코드'] == row['팀코드']) & (team_pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['P/IP'] = 0
        return row
    previous_sum = previous.sum()
    try:
        pg = previous_sum["투구수"]/(previous_sum["이닝*3"]/3)
    except ZeroDivisionError:
        row['P/IP'] = 0
    row["P/IP"] = pg
    return row
def perPIP(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    previous_sum = previous.sum()
    if len(previous) == 0:
        row['P/IP'] = 0
        return row
    try:
        pg = previous_sum["투구수"]/(previous_sum["이닝*3"]/3)
    except ZeroDivisionError:
        row['P/IP'] = 0
        return row
    row['P/IP'] = pg
    return row

In [132]:
team_pitcher = team_pitcher.apply(pip,axis=1)
team_pitcher["P/IP"].tail()

6395    16.668088
6396    16.638404
6397    17.362611
6398    17.631235
6399    16.562718
Name: P/IP, dtype: float64

In [133]:
pitcher = pitcher.apply(perPIP,axis=1)
pitcher["P/IP"]

0         0.000000
1         0.000000
2         0.000000
3         0.000000
4         0.000000
           ...
27799    16.782609
27800    17.197183
27801    14.785714
27802    18.103448
27803    17.000000
Name: P/IP, Length: 27804, dtype: float64

In [134]:
def ppa(row):
    previous = team_pitcher[(team_pitcher['시즌'] == row['시즌']) & (team_pitcher['팀코드'] == row['팀코드']) & (team_pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['P/PA'] = 0
        return row
    previous_sum = previous.sum()
    try:
        pg = previous_sum["투구수"]/previous_sum["타자"]
    except ZeroDivisionError:
        row['P/PA'] = 0
    row["P/PA"] = pg
    return row
def perPPA(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    previous_sum = previous.sum()
    if len(previous) == 0:
        row['P/PA'] = 0
        return row
    try:
        pg = previous_sum["투구수"]/previous_sum["타자"]
    except ZeroDivisionError:
        row['P/PA'] = 0
        return row
    row['P/PA'] = pg
    return row

In [135]:
team_pitcher = team_pitcher.apply(ppa,axis=1)
team_pitcher["P/PA"].tail()

6395    3.842881
6396    3.881326
6397    3.879077
6398    3.933625
6399    3.825755
Name: P/PA, dtype: float64

In [136]:
pitcher = pitcher.apply(perPPA,axis=1)
pitcher["P/PA"]

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
27799    3.938776
27800    3.990196
27801    3.729730
27802    3.301887
27803    3.923077
Name: P/PA, Length: 27804, dtype: float64

In [137]:
team_pitcher.to_csv("팀투수_세이버 매트릭스_합본.csv",encoding='utf-8-sig')

In [138]:
pitcher.to_csv("개인투수_세이버 매트릭스_합본.csv",encoding='utf-8-sig')

In [139]:
team_pitcher

,Unnamed: 0,Unnamed: 0.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,완투,결과,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,0,W,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,20160401HHLG0,2016-04-01,HH,LG,0,T,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,20160401HTNC0,2016-04-01,NC,HT,0,B,0,W,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,20160401HTNC0,2016-04-01,HT,NC,0,T,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,20160401KTSK0,2016-04-01,SK,KT,0,B,0,L,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,6395,635,20200719LTSS0,2020-07-19,LT,SS,0,T,0,W,...,0.679640,0.030008,0.174134,6.774665,3.091352,1.167479,2.191489,149.557377,16.668088,3.842881
6396,6396,636,20200719OBHT0,2020-07-19,HT,OB,0,B,0,L,...,0.684932,0.020524,0.199127,7.675810,3.114090,0.791147,2.464865,145.836066,16.638404,3.881326
6397,6397,637,20200719OBHT0,2020-07-19,OB,HT,0,T,0,W,...,0.654102,0.019154,0.166800,6.697923,3.188724,0.769139,2.100503,154.793651,17.362611,3.879077
6398,6398,638,20200719WOSK0,2020-07-19,SK,WO,0,B,0,W,...,0.683666,0.023089,0.176354,7.102732,4.248812,0.929929,1.671698,154.640625,17.631235,3.933625
6399,6399,639,20200719WOSK0,2020-07-19,WO,SK,0,T,0,L,...,0.679494,0.026994,0.167204,6.506969,2.696864,1.050523,2.412791,146.261538,16.562718,3.825755

In [140]:
pitcher

,Unnamed: 0,Unnamed: 0.1,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,선발,...,LOB,홈런율,삼진율,K9,BB9,HR9,KBB,P/G,P/IP,P/PA
0,0,0,20160401HHLG0,2016-04-01,LG,HH,0,B,60146,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,1,20160401HHLG0,2016-04-01,LG,HH,0,B,61891,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,2,20160401HHLG0,2016-04-01,LG,HH,0,B,62146,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,3,20160401HHLG0,2016-04-01,LG,HH,0,B,62698,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,4,20160401HHLG0,2016-04-01,HH,LG,0,T,65764,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27799,27799,2882,20200719WOSK0,2020-07-19,WO,SK,0,T,67313,1,...,0.763889,0.030928,0.185567,7.043478,3.130435,1.173913,2.250000,146.261538,16.782609,3.938776
27800,27800,2883,20200719WOSK0,2020-07-19,WO,SK,0,T,67391,0,...,0.614035,0.019608,0.205882,7.985915,3.422535,0.760563,2.333333,146.261538,17.197183,3.990196
27801,27801,2884,20200719WOSK0,2020-07-19,WO,SK,0,T,68341,0,...,0.697674,0.027027,0.270270,9.642857,4.821429,0.964286,2.000000,146.261538,14.785714,3.729730
27802,27802,2885,20200719WOSK0,2020-07-19,WO,SK,0,T,69399,0,...,0.461538,0.000000,0.075472,3.724138,3.724138,0.000000,1.000000,146.261538,18.103448,3.301887
27803,27803,2886,20200719WOSK0,2020-07-19,SK,WO,0,B,75138,0,...,0.869565,0.076923,0.153846,6.000000,6.000000,3.000000,1.000000,154.640625,17.000000,3.923077